markdown: kramdown
pygments: true
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: Singco
subTitle: This is Yunke Sun' site!
description: 孙云柯，中国传媒大学传播学传播研究方法研究生，师从沈浩教授，关注数据新闻、数据可视化和数据挖掘领域。
url: http://singco.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 分类
    url: /category.html  
  - text: 作品
    url: /works.html
  - text: 关于我
    url: /about.html
  - text: 博客源代码
    url: https://github.com/singco/singco.github.io

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url: http://www.zhanxin.info
  - class: fa-facebook
    url: https://www.facebook.com/singcosun
  - class: fa-github
    url: http://github.com/singco
  - class: fa-weibo
    url: http://weibo.com/singco890826
  - class: fa-renren
    url: http://www.renren.com/sunyunke0826
  - class: fa-pinterest
    url: http://www.zhanxin.info
  - class: fa-twitter
    url: https://twitter.com/singco890826
  - class: fa-rss
    url: http://www.zhanxin.info

#作者信息
author:
  link: http://www.zhanxin.info/contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1

#评论信息
disqus:
  config: true
  id: piznblog

duoshuo:
  config: false
  id: zhanxin