markdown: rdiscount
pygments: true
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: singco
subTitle: Welcome to singco's site
description: 这里是云柯的小站
url: http://localhost:4000
feed: /atom.xml
twitter_username: singco
github_username:  singco

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 文章归档
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: 关于我
    url: /contact.html
    icon: icon-envelope-alt
    class: none
  - text: 联系我
    url: http://www.zhanxin.info/contact.html
    icon: icon-heart
    class: none
  - text: 博客源代码
    url: https://github.com/pizn/iLotus
    icon: icon-github
    class: none

page:
  - text: 文章分类
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact.html
    last: false

author:
  name: singco
