markdown: rdiscount
pygments: true
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: singco
subTitle: Welcome to singco's site
description: I'd always heard your entire life flashes in front of your eyes the second before you die.
url: http://weibo.com/singco890826
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 作品
    url: /works.html
  - text: 联系我
    url: http://www.zhanxin.info/contact.html
  - text: 博客源代码
    url: https://github.com/pizn/pizn.github.com

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url: http://www.zhanxin.info
  - class: fa-facebook
    url: http://www.zhanxin.info
  - class: fa-github
    url: http://github.com/singco
  - class: fa-weibo
    url: http://weibo.com/singco
  - class: fa-renren
    url: http://www.zhanxin.info
  - class: fa-pinterest
    url: http://www.zhanxin.info
  - class: fa-twitter
    url: http://www.zhanxin.info
  - class: fa-rss
    url: http://www.zhanxin.info

#作者信息
author:
  link: http://www.zhanxin.info/contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1

#评论信息
disqus:
  config: true
  id: piznblog

duoshuo:
  config: false
  id: zhanxin